name: example-build

on:
  push: {}
  workflow_dispatch: {}

env:
  TARGET_USER_NAME: test
  IMAGE_NAME: image

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        has-output:
          - true
          - false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: GitHub Contexts
        run: |
          echo "---------"
          echo "current-dir: ${PWD}"
          echo "---------"
          echo "${JSON_VALUE}"
        env:
          JSON_VALUE: "${{ toJson(github) }}"

      - name: Set Output
        id: exp
        if: ${{ matrix.has-output }}
        run: echo "value=test" >> "${GITHUB_OUTPUT}"

      - name: Show Output
        run: echo "test=${{ steps.exp.outputs.value }}"
