name: example-build

on:
  push: {}

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: GitHub Contexts
        run: echo "${JSON_VALUE}"
        env:
          JSON_VALUE: "${{ toJson(github) }}"

#      - uses: hadolint/hadolint-action@v3.1.0
#        name: Runs hadolint



