name: example-build

on:
  push: {}

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: GitHub Contexts
        run: |
          echo "---------"
          echo "current-dir: ${PWD}"
          echo "---------"
          echo "${JSON_VALUE}"
        env:
          JSON_VALUE: "${{ toJson(github) }}"

      - uses: docker/build-push-action@v5
        name: Build an image then push it to GitHub registry
        with:
          context: .
          platforms: linux/amd64
          push: false

#      - uses: hadolint/hadolint-action@v3.1.0
#        name: Runs hadolint



