name: example-build

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  TARGET_USER_NAME: test
  IMAGE_NAME: image

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        has-output:
          - true
          - false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: GitHub Contexts
        run: |
          echo "---------"
          echo "current-dir: ${PWD}"
          echo "---------"
          echo "${JSON_VALUE}"
        env:
          JSON_VALUE: "${{ toJson(github) }}"
