name: example-build

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  TARGET_USER_NAME: test
  IMAGE_NAME: image

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        has-output:
          - true
          - false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: GitHub Contexts
        run: |
          echo "---------"
          echo "current-dir: ${PWD}"
          echo "---------"
          echo "${JSON_VALUE}"
        env:
          JSON_VALUE: "${{ toJson(github) }}"

      - name: Run If pull_request
        if: ${{ github.event.pull_request }}
        id: with-pr
        run: echo "value=${{ github.event.pull_request.issue_url }}" > "${GITHUB_OUTPUT}"

      - name: Run If with-pr has value
        run: |
          function countArgs() {
            echo "${#}"
            if [[ -n "${1}" ]]; then
              echo "not empty: ${1}"
            else
              echo "empty: ${1}"
            fi
          }
          countArgs "${{ steps.with-pr.outputs.value }}"
          countArgs "${{ steps.with-pr.outputs.value || github.event.number }}"

